using System.Globalization;
using System.Text;

namespace TypedJint;

public enum JavaScriptCSharpGenerationMode
{
    StaticClass,
    TopLevelStatements,
    RuntimeTopLevelStatements
}

public sealed record JavaScriptCSharpGenerationOptions(
    JavaScriptCSharpGenerationMode Mode = JavaScriptCSharpGenerationMode.StaticClass,
    string ClassName = "ScriptModule",
    bool IncludeNullable = true,
    bool IncludeTypedJintUsing = true);

public static class JavaScriptCSharpGenerator
{
    public static string Generate(string source, JavaScriptCSharpGenerationOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(source);
        options ??= new JavaScriptCSharpGenerationOptions();

        return options.Mode switch
        {
            JavaScriptCSharpGenerationMode.StaticClass => EnsureSystemUsing(CSharpIntrinsicRewriter.Rewrite(TypedJintTranspiler.TranspileToCSharp(source, options.ClassName))),
            JavaScriptCSharpGenerationMode.TopLevelStatements => GenerateTopLevelStatements(source, options),
            JavaScriptCSharpGenerationMode.RuntimeTopLevelStatements => GenerateRuntimeTopLevelStatements(source, options),
            _ => throw new ArgumentOutOfRangeException(nameof(options), options.Mode, null)
        };
    }

    public static string GenerateStaticClass(string source, string className = "ScriptModule") =>
        Generate(source, new JavaScriptCSharpGenerationOptions(JavaScriptCSharpGenerationMode.StaticClass, className));

    public static string GenerateTopLevelStatements(string source) =>
        Generate(source, new JavaScriptCSharpGenerationOptions(JavaScriptCSharpGenerationMode.TopLevelStatements));

    public static string GenerateRuntimeTopLevelStatements(string source) =>
        Generate(source, new JavaScriptCSharpGenerationOptions(JavaScriptCSharpGenerationMode.RuntimeTopLevelStatements));

    private static string GenerateTopLevelStatements(string source, JavaScriptCSharpGenerationOptions options)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        if (options.IncludeNullable)
        {
            builder.AppendLine("#nullable enable");
        }

        builder.AppendLine("using System;");

        if (options.IncludeTypedJintUsing)
        {
            builder.AppendLine("using TypedJint;");
        }

        builder.AppendLine();

        var functions = SimpleJsParser.ParseFunctions(source);
        foreach (var function in functions)
        {
            builder.AppendLine(ToLocalFunction(CSharpIntrinsicRewriter.Rewrite(TypedJintTranspiler.TranspileFunctionToCSharp(function))));
        }

        var globalSource = RemoveFunctionDeclarations(source, functions).Trim();
        if (globalSource.Length > 0)
        {
            var statements = new StatementParser(globalSource).ParseStatements();
            foreach (var statement in statements)
            {
                EmitStatement(builder, statement, indent: 0);
            }
        }

        return CSharpIntrinsicRewriter.Rewrite(builder.ToString());
    }

    private static string GenerateRuntimeTopLevelStatements(string source, JavaScriptCSharpGenerationOptions options)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        if (options.IncludeNullable)
        {
            builder.AppendLine("#nullable enable");
        }

        builder.AppendLine("using TypedJint;");
        builder.AppendLine();
        builder.AppendLine("var engine = new JavaScriptRuntimeEngine();");
        builder.Append("engine.Execute(").Append(ToRawStringLiteral(source)).AppendLine(");");
        return builder.ToString();
    }

    private static string ToLocalFunction(string methodSource)
    {
        var lines = methodSource.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var builder = new StringBuilder();
        foreach (var line in lines)
        {
            if (line.StartsWith("public static ", StringComparison.Ordinal))
            {
                builder.AppendLine(line[14..]);
            }
            else
            {
                builder.AppendLine(line);
            }
        }

        return builder.ToString();
    }

    private static string RemoveFunctionDeclarations(string source, IReadOnlyList<JsFunctionDeclaration> functions)
    {
        if (functions.Count == 0)
        {
            return source;
        }

        var ordered = functions.OrderBy(x => x.Span.Start).ToArray();
        var builder = new StringBuilder(source.Length);
        var offset = 0;
        foreach (var function in ordered)
        {
            if (function.Span.Start > offset)
            {
                builder.Append(source, offset, function.Span.Start - offset);
            }

            offset = function.Span.Start + function.Span.Length;
        }

        if (offset < source.Length)
        {
            builder.Append(source, offset, source.Length - offset);
        }

        return builder.ToString();
    }

    private static string ToRawStringLiteral(string value)
    {
        var quotes = 3;
        while (value.Contains(new string('"', quotes), StringComparison.Ordinal))
        {
            quotes++;
        }

        var fence = new string('"', quotes);
        return fence + Environment.NewLine + value + Environment.NewLine + fence;
    }

    private static void EmitStatement(StringBuilder builder, JsStatement statement, int indent)
    {
        var pad = Pad(indent);
        switch (statement)
        {
            case JsBlockStatement block:
                builder.Append(pad).AppendLine("{");
                foreach (var child in block.Statements)
                {
                    EmitStatement(builder, child, indent + 1);
                }

                builder.Append(pad).AppendLine("}");
                break;

            case JsVariableStatement variable:
                builder.Append(pad).Append("var ").Append(SanitizeIdentifier(variable.Name)).Append(" = ").Append(EmitExpression(variable.Initializer)).AppendLine(";");
                break;

            case JsReturnStatement ret:
                builder.Append(pad).Append("return");
                if (ret.Value is not null)
                {
                    builder.Append(' ').Append(EmitExpression(ret.Value));
                }

                builder.AppendLine(";");
                break;

            case JsExpressionStatement expression:
                builder.Append(pad).Append(EmitExpression(expression.Expression)).AppendLine(";");
                break;

            case JsAssignmentStatement assignment:
                builder.Append(pad).Append(EmitExpression(assignment.Target)).Append(" = ").Append(EmitExpression(assignment.Value)).AppendLine(";");
                break;

            case JsCompoundAssignmentStatement assignment:
                builder.Append(pad).Append(EmitExpression(assignment.Target)).Append(' ').Append(assignment.Operator).Append(' ').Append(EmitExpression(assignment.Value)).AppendLine(";");
                break;

            case JsIfStatement ifStatement:
                builder.Append(pad).Append("if (").Append(EmitExpression(ifStatement.Test)).AppendLine(")");
                EmitEmbeddedStatement(builder, ifStatement.Consequent, indent);
                if (ifStatement.Alternate is not null)
                {
                    builder.Append(pad).AppendLine("else");
                    EmitEmbeddedStatement(builder, ifStatement.Alternate, indent);
                }
                break;

            case JsWhileStatement whileStatement:
                builder.Append(pad).Append("while (").Append(EmitExpression(whileStatement.Test)).AppendLine(")");
                EmitEmbeddedStatement(builder, whileStatement.Body, indent);
                break;

            case JsForStatement forStatement:
                builder.Append(pad)
                    .Append("for (")
                    .Append(EmitForPart(forStatement.Init))
                    .Append("; ")
                    .Append(forStatement.Test is null ? string.Empty : EmitExpression(forStatement.Test))
                    .Append("; ")
                    .Append(EmitForPart(forStatement.Update))
                    .AppendLine(")");
                EmitEmbeddedStatement(builder, forStatement.Body, indent);
                break;

            case JsBreakStatement:
                builder.Append(pad).AppendLine("break;");
                break;

            case JsContinueStatement:
                builder.Append(pad).AppendLine("continue;");
                break;

            default:
                builder.Append(pad).Append("// unsupported: ").AppendLine(statement.GetType().Name);
                break;
        }
    }

    private static void EmitEmbeddedStatement(StringBuilder builder, JsStatement statement, int indent)
    {
        if (statement is JsBlockStatement)
        {
            EmitStatement(builder, statement, indent);
            return;
        }

        builder.Append(Pad(indent)).AppendLine("{");
        EmitStatement(builder, statement, indent + 1);
        builder.Append(Pad(indent)).AppendLine("}");
    }

    private static string EmitForPart(JsStatement? statement)
    {
        return statement switch
        {
            null => string.Empty,
            JsVariableStatement variable => "var " + SanitizeIdentifier(variable.Name) + " = " + EmitExpression(variable.Initializer),
            JsAssignmentStatement assignment => EmitExpression(assignment.Target) + " = " + EmitExpression(assignment.Value),
            JsCompoundAssignmentStatement assignment => EmitExpression(assignment.Target) + " " + assignment.Operator + " " + EmitExpression(assignment.Value),
            JsExpressionStatement expression => EmitExpression(expression.Expression),
            _ => statement.GetType().Name
        };
    }

    private static string EmitExpression(JsExpression expression)
    {
        return expression switch
        {
            JsLiteralExpression { Value: null } => "null",
            JsLiteralExpression { Value: string text } => FormatStringLiteral(text),
            JsLiteralExpression { Value: bool value } => value ? "true" : "false",
            JsLiteralExpression { Value: double value } => value.ToString("R", CultureInfo.InvariantCulture),
            JsLiteralExpression literal => Convert.ToString(literal.Value, CultureInfo.InvariantCulture) ?? string.Empty,
            JsIdentifierExpression identifier => SanitizeIdentifier(identifier.Name),
            JsMemberExpression member => EmitExpression(member.Target) + "." + member.Member,
            JsIndexExpression index => EmitExpression(index.Target) + "[" + EmitExpression(index.Index) + "]",
            JsCallExpression call => EmitExpression(call.Target) + "(" + string.Join(", ", call.Arguments.Select(EmitExpression)) + ")",
            JsBinaryExpression binary => "(" + EmitExpression(binary.Left) + " " + MapOperator(binary.Operator) + " " + EmitExpression(binary.Right) + ")",
            JsUnaryExpression unary => "(" + unary.Operator + EmitExpression(unary.Operand) + ")",
            JsUpdateExpression update => update.Prefix ? update.Operator + EmitExpression(update.Target) : EmitExpression(update.Target) + update.Operator,
            JsArrayExpression array => "new[] { " + string.Join(", ", array.Elements.Select(EmitExpression)) + " }",
            JsConditionalExpression conditional => "(" + EmitExpression(conditional.Test) + " ? " + EmitExpression(conditional.Consequent) + " : " + EmitExpression(conditional.Alternate) + ")",
            _ => expression.GetType().Name
        };
    }

    private static string MapOperator(string op) => op switch { "===" => "==", "!==" => "!=", _ => op };

    private static string FormatStringLiteral(string value) =>
        "\"" + value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal) + "\"";

    private static string SanitizeIdentifier(string value) => value switch
    {
        "class" or "namespace" or "public" or "private" or "protected" or "internal" or "static" or "void" or "double" or "string" or "bool" or "object" or "return" => "@" + value,
        _ => value
    };

    private static string EnsureSystemUsing(string source)
    {
        if (source.Contains("using System;", StringComparison.Ordinal))
        {
            return source;
        }

        return source.Replace("#nullable enable" + Environment.NewLine, "#nullable enable" + Environment.NewLine + "using System;" + Environment.NewLine, StringComparison.Ordinal);
    }

    private static string Pad(int indent) => new(' ', indent * 4);
}
