using System.Text;
using System.Text.RegularExpressions;

namespace TypedJint;

public sealed record OptimizedJavaScriptCSharpGenerationOptions(
    string ClassName = "ScriptModule",
    bool EmitNativeMethods = true,
    bool EmitRuntimeFallback = true,
    bool EmitAggressiveInlining = true,
    bool IncludeNullable = true);

public sealed record OptimizedJavaScriptCSharpGenerationResult(
    string Source,
    IReadOnlyList<string> NativeFunctions,
    IReadOnlyList<string> RuntimeFunctions,
    IReadOnlyList<TypedDiagnostic> Diagnostics);

public static class OptimizedJavaScriptCSharpGenerator
{
    private static readonly Regex FunctionHeaderRegex = new(@"(?<doc>/\*\*[\s\S]*?\*/\s*)?function\s+(?<name>[A-Za-z_$][A-Za-z0-9_$]*)\s*\((?<params>[^)]*)\)\s*\{", RegexOptions.Compiled);

    public static OptimizedJavaScriptCSharpGenerationResult Generate(
        string source,
        OptimizedJavaScriptCSharpGenerationOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(source);
        options ??= new OptimizedJavaScriptCSharpGenerationOptions();

        var diagnostics = new List<TypedDiagnostic>();
        var nativeFunctions = options.EmitNativeMethods
            ? CollectNativeFunctions(source, diagnostics)
            : Array.Empty<JsFunctionDeclaration>();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        if (options.IncludeNullable)
        {
            builder.AppendLine("#nullable enable");
        }

        builder.AppendLine("using System;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("using TypedJint;");
        builder.AppendLine();
        builder.Append("public sealed class ").Append(SanitizeIdentifier(options.ClassName)).AppendLine();
        builder.AppendLine("{");

        if (options.EmitRuntimeFallback)
        {
            builder.AppendLine("    private readonly JavaScriptRuntimeEngine _runtime;");
            builder.AppendLine();
            builder.Append("    private const string Source = ").Append(ToRawStringLiteral(source, indent: 4)).AppendLine(";");
            builder.AppendLine();
            builder.Append("    public ").Append(SanitizeIdentifier(options.ClassName)).AppendLine("()");
            builder.AppendLine("    {");
            builder.AppendLine("        _runtime = new JavaScriptRuntimeEngine();");
            builder.AppendLine("        _runtime.Execute(Source);");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public JavaScriptRuntimeEngine Runtime => _runtime;");
            builder.AppendLine();
            builder.AppendLine("    public object? Invoke(string functionName, params object?[] arguments) => _runtime.Invoke(functionName, arguments);");
            builder.AppendLine();
            builder.AppendLine("    public object? Evaluate(string expression) => _runtime.Evaluate(expression);");
            builder.AppendLine();
        }
        else
        {
            builder.Append("    public ").Append(SanitizeIdentifier(options.ClassName)).AppendLine("()");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        var emittedNative = new List<string>();
        foreach (var function in nativeFunctions)
        {
            EmitNativeMethod(builder, function, options);
            emittedNative.Add(function.Name);
        }

        builder.AppendLine("}");

        var runtimeFunctions = JavaScriptDeclarationScanner.Scan(source).Functions
            .Where(x => !emittedNative.Contains(x, StringComparer.Ordinal))
            .ToArray();

        return new OptimizedJavaScriptCSharpGenerationResult(
            builder.ToString(),
            emittedNative,
            runtimeFunctions,
            diagnostics);
    }

    private static IReadOnlyList<JsFunctionDeclaration> CollectNativeFunctions(string source, List<TypedDiagnostic> diagnostics)
    {
        var functions = new List<JsFunctionDeclaration>();
        var position = 0;
        while (position < source.Length)
        {
            var match = FunctionHeaderRegex.Match(source, position);
            if (!match.Success)
            {
                break;
            }

            try
            {
                var bodyStart = match.Index + match.Length;
                var bodyEnd = FindMatchingBrace(source, bodyStart - 1);
                var functionSource = source.Substring(match.Index, bodyEnd - match.Index + 1);
                var parsed = SimpleJsParser.ParseFunctions(functionSource).SingleOrDefault();
                if (parsed is not null && IsNativelyCompilable(functionSource, parsed.Name, diagnostics))
                {
                    functions.Add(parsed);
                }

                position = bodyEnd + 1;
            }
            catch (Exception ex)
            {
                diagnostics.Add(new TypedDiagnostic(
                    "TJ2001",
                    TypedDiagnosticSeverity.Warning,
                    $"Native C# generation skipped function near offset {match.Index}: {ex.Message}"));
                position = match.Index + match.Length;
            }
        }

        return functions;
    }

    private static bool IsNativelyCompilable(string functionSource, string functionName, List<TypedDiagnostic> diagnostics)
    {
        try
        {
            var compileResult = new TypedJsCompiler(
                new Dictionary<string, object?>(StringComparer.Ordinal),
                new TypedJintOptions { ThrowOnCompilationFailure = false }).Compile(functionSource);

            diagnostics.AddRange(compileResult.Diagnostics);
            return compileResult.CompiledFunctions.ContainsKey(functionName);
        }
        catch (Exception ex)
        {
            diagnostics.Add(new TypedDiagnostic(
                "TJ2002",
                TypedDiagnosticSeverity.Warning,
                $"Native C# generation skipped function '{functionName}': {ex.Message}"));
            return false;
        }
    }

    private static int FindMatchingBrace(string source, int openBrace)
    {
        var depth = 0;
        var inString = false;
        var quote = '\0';
        for (var i = openBrace; i < source.Length; i++)
        {
            var c = source[i];
            if (inString)
            {
                if (c == quote && (i == 0 || source[i - 1] != '\\'))
                {
                    inString = false;
                }
                continue;
            }

            if (c is '\'' or '"')
            {
                inString = true;
                quote = c;
                continue;
            }

            if (c == '{') depth++;
            if (c == '}') depth--;
            if (depth == 0) return i;
        }

        throw new FormatException("Unterminated function body.");
    }

    private static void EmitNativeMethod(StringBuilder builder, JsFunctionDeclaration function, OptimizedJavaScriptCSharpGenerationOptions options)
    {
        var method = TypedJintTranspiler.TranspileFunctionToCSharp(function)
            .Replace("public static ", "public ", StringComparison.Ordinal)
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n');

        if (options.EmitAggressiveInlining)
        {
            builder.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        }

        foreach (var line in method)
        {
            if (line.Length == 0)
            {
                builder.AppendLine();
            }
            else
            {
                builder.Append("    ").AppendLine(line);
            }
        }

        builder.AppendLine();
    }

    private static string ToRawStringLiteral(string value, int indent)
    {
        var quotes = 3;
        while (value.Contains(new string('"', quotes), StringComparison.Ordinal))
        {
            quotes++;
        }

        var fence = new string('"', quotes);
        var pad = new string(' ', indent);
        var lines = value.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var builder = new StringBuilder();
        builder.AppendLine(fence);
        foreach (var line in lines)
        {
            builder.Append(pad).AppendLine(line);
        }

        builder.Append(pad).Append(fence);
        return builder.ToString();
    }

    private static string SanitizeIdentifier(string value) => value switch
    {
        "class" or "namespace" or "public" or "private" or "protected" or "internal" or "static" or "void" or "double" or "string" or "bool" or "object" or "return" => "@" + value,
        _ => value
    };
}
