using System.Text;

namespace TypedJint;

public sealed record OptimizedJavaScriptCSharpGenerationOptions(
    string ClassName = "ScriptModule",
    bool EmitNativeMethods = true,
    bool EmitRuntimeFallback = true,
    bool EmitAggressiveInlining = true,
    bool IncludeNullable = true);

public sealed record OptimizedJavaScriptCSharpGenerationResult(
    string Source,
    IReadOnlyList<string> NativeFunctions,
    IReadOnlyList<string> RuntimeFunctions,
    IReadOnlyList<TypedDiagnostic> Diagnostics);

public static class OptimizedJavaScriptCSharpGenerator
{
    public static OptimizedJavaScriptCSharpGenerationResult Generate(
        string source,
        OptimizedJavaScriptCSharpGenerationOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(source);
        options ??= new OptimizedJavaScriptCSharpGenerationOptions();

        var diagnostics = new List<TypedDiagnostic>();
        var nativeFunctions = Array.Empty<JsFunctionDeclaration>();
        var compiledNames = new HashSet<string>(StringComparer.Ordinal);

        if (options.EmitNativeMethods)
        {
            try
            {
                nativeFunctions = SimpleJsParser.ParseFunctions(source).ToArray();
                var compileResult = new TypedJsCompiler(
                    new Dictionary<string, object?>(StringComparer.Ordinal),
                    new TypedJintOptions { ThrowOnCompilationFailure = false }).Compile(source);

                foreach (var name in compileResult.CompiledFunctions.Keys)
                {
                    compiledNames.Add(name);
                }

                diagnostics.AddRange(compileResult.Diagnostics);
            }
            catch (Exception ex)
            {
                diagnostics.Add(new TypedDiagnostic(
                    "TJ2001",
                    TypedDiagnosticSeverity.Warning,
                    "Native C# generation was skipped because the source contains syntax outside the typed compiler subset: " + ex.Message));
            }
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        if (options.IncludeNullable)
        {
            builder.AppendLine("#nullable enable");
        }

        builder.AppendLine("using System;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("using TypedJint;");
        builder.AppendLine();
        builder.Append("public sealed class ").Append(SanitizeIdentifier(options.ClassName)).AppendLine();
        builder.AppendLine("{");

        if (options.EmitRuntimeFallback)
        {
            builder.AppendLine("    private readonly JavaScriptRuntimeEngine _runtime;");
            builder.AppendLine();
            builder.Append("    private const string Source = ").Append(ToRawStringLiteral(source, indent: 4)).AppendLine(";");
            builder.AppendLine();
            builder.Append("    public ").Append(SanitizeIdentifier(options.ClassName)).AppendLine("()");
            builder.AppendLine("    {");
            builder.AppendLine("        _runtime = new JavaScriptRuntimeEngine();");
            builder.AppendLine("        _runtime.Execute(Source);");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public JavaScriptRuntimeEngine Runtime => _runtime;");
            builder.AppendLine();
            builder.AppendLine("    public object? Invoke(string functionName, params object?[] arguments) => _runtime.Invoke(functionName, arguments);");
            builder.AppendLine();
            builder.AppendLine("    public object? Evaluate(string expression) => _runtime.Evaluate(expression);");
            builder.AppendLine();
        }
        else
        {
            builder.Append("    public ").Append(SanitizeIdentifier(options.ClassName)).AppendLine("()");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        var emittedNative = new List<string>();
        foreach (var function in nativeFunctions.Where(x => compiledNames.Contains(x.Name)))
        {
            EmitNativeMethod(builder, function, options);
            emittedNative.Add(function.Name);
        }

        builder.AppendLine("}");

        var runtimeFunctions = JavaScriptDeclarationScanner.Scan(source).Functions
            .Where(x => !emittedNative.Contains(x, StringComparer.Ordinal))
            .ToArray();

        return new OptimizedJavaScriptCSharpGenerationResult(
            builder.ToString(),
            emittedNative,
            runtimeFunctions,
            diagnostics);
    }

    private static void EmitNativeMethod(StringBuilder builder, JsFunctionDeclaration function, OptimizedJavaScriptCSharpGenerationOptions options)
    {
        var method = TypedJintTranspiler.TranspileFunctionToCSharp(function)
            .Replace("public static ", "public ", StringComparison.Ordinal)
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n');

        if (options.EmitAggressiveInlining)
        {
            builder.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        }

        foreach (var line in method)
        {
            if (line.Length == 0)
            {
                builder.AppendLine();
            }
            else
            {
                builder.Append("    ").AppendLine(line);
            }
        }

        builder.AppendLine();
    }

    private static string ToRawStringLiteral(string value, int indent)
    {
        var quotes = 3;
        while (value.Contains(new string('"', quotes), StringComparison.Ordinal))
        {
            quotes++;
        }

        var fence = new string('"', quotes);
        var pad = new string(' ', indent);
        var lines = value.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var builder = new StringBuilder();
        builder.AppendLine(fence);
        foreach (var line in lines)
        {
            builder.Append(pad).AppendLine(line);
        }

        builder.Append(pad).Append(fence);
        return builder.ToString();
    }

    private static string SanitizeIdentifier(string value) => value switch
    {
        "class" or "namespace" or "public" or "private" or "protected" or "internal" or "static" or "void" or "double" or "string" or "bool" or "object" or "return" => "@" + value,
        _ => value
    };
}
