name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore TypedJint.sln
      - name: Build
        run: dotnet build TypedJint.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test TypedJint.sln --configuration Release --no-build
